name: geo_firestore_flutter
description: GeoFirestore for Flutter to do location based queries with Firestore
homepage: https://github.com/ngxingyu/geo_firestore
version: 0.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.0
  cloud_firestore: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito: ^5.0.4
